export const SUCCESS_MESSAGE = {
  USER_LOGGED_IN: "User_Successfully_Logged_In",
  FAILED_LOGGED_IN: "User_Failed_To_Logged_In",
  PRODUCT_SUCCESSFULLY_CREATED: "Product_Successfully_Created",
  FAILED_TO_CREATE_PRODUCT: "Failed_To_Create_Product",
  USER_REGISTERED_SUCCESSFULLY: "User_Registered_Successfully",
  USER_REGISTRATION_FAILED: "User_Registration_Failed",
  PRODUCT_LIST: "Product_List",
  PRODUCT_LISTING_FAILED: "Product_Listing_Failed",
  PRODUCT_DETAILS: "Product_Details",
  PRODUCT_DETAILS_FAILED: "Getting_Product_Details_Failed",
  PRODUCT_UPDATED: "Product_Updated",
  FAILED_UPDATING_PRODUCT: "Failed_Updating_Product",
  PRODUCT_DELETED: "Product_Deleted",
  FAILED_DELETING_PRODUCT: "Failed_Deleting_Product",
};
